### ISSUE TITLE
Received status code 401 from server: Unauthorized

### ISSUE THREAD

**Issue by NihalGurzu** [cftc01/PCI-SDK-Android#1]
### Error occurred
Could not GET 'https://maven.pkg.github.com/cftc01/PCI-SDK-Android/com/cascade/pci-sdk/1.0.0/pci-sdk-1.0.0.pom'. Received status code 401 from server: Unauthorized

### Project configuration
**Settings.gradle**
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven {
            name = "GitHubPackages"
            url = uri('https://maven.pkg.github.com/cftc01/PCI-SDK-Android')
        }
}
```

**build.grade(:app)**
```
    implementation 'com.cascade:pci-sdk:1.0.0'
```

### Similar issue/discussion found:
**[Stackoverflow](https://stackoverflow.com/questions/60400637/401-unauthorized-downloading-a-public-package-from-github-packages-using-gradle)** - similar issue that we are currently facing
**[Github community](https://github.com/orgs/community/discussions/26634)** - open discussion

Most of the examples/guide we found contains credentials with username and password for authentication. 
Something like this:
```
maven {
  url "https://maven.pkg.github.com/name/package-name"
  credentials {
    username GITHUB_USER
    password GITHUB_TOKEN
  }
}
```
### Is there anything that we may have missed? @mdiener

**Comment by mdiener** [comment]
I've changed how the package is being accessed and pivoted away from GitHub packages. You can now access it simply through adding

```
maven { url 'https://raw.githubusercontent.com/cftc01/PCI-SDK-Android/master/maven' }
```

to your repositories.
