### ISSUE TITLE
Displayed loading state when an instance is called

### ISSUE THREAD

**Issue by kiransharmaaa** [cftc01/PCI-SDK-Android#4]
**Error occurred**
We are currently experiencing an issue with the Cascade SDK in our project. When attempting to perform an instance (Show card image, set pin, activate card)  method, the screen goes into a loading state and never displays the image.

**Project configuration**
The SDK is being initialized with the following configuration:
```
 CascadeSDK.initialize(
            context = context,
            preSharedKey = preSharedKeyData,
            apiUrl = apiUrl,
            ivCallback = object : IVCallback {
                override suspend fun getIv(cardId: String): Pair<String, ByteArray> =
                    suspendCoroutine { cont ->
                        cont.resume(Pair(ivIdData, ivData))
                    }
            },
        )
```

**When an instance is called** 
```
fun showCard (){
CascadeSDK.getInstance().showCardImage(context, cardID")
} //goes on loading state without showing the card
```

Is there anything that we may have missed? @mdiener

**Here is the screenshot of the screen in the loading state**
<img width="223" alt="Screenshot 2023-01-16 at 13 57 08" src="https://user-images.githubusercontent.com/99158962/212649739-4e2bd999-8231-4e01-bfac-654c0f252115.png">

**Comment by mdiener** [comment]
Closed this issue as it is resolved. This happens when an invalid IV is provided to the SDK on repeat requests.
